# Generated by Django 3.0.6 on 2020-07-16 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_item',
            old_name='Product',
            new_name='product',
        ),
    ]
