# Generated by Django 3.0.6 on 2020-07-16 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200716_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_item',
            old_name='product',
            new_name='Product',
        ),
    ]
