# Generated by Django 3.0.6 on 2020-07-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_product_digital'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mrp',
            field=models.FloatField(null=True),
        ),
    ]
